version: '3'

services:
  postgres-docker:
    image: postgres:latest
    environment:
      POSTGRES_DB: kanver
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  kanver-app:
    image: kanver:0.0.1-SNAPSHOT
    depends_on:
      - postgres-docker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-docker:5432/kanver
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
