spring:
  cors:
    allowed-origins:
      - "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/kanver
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
