spring:
  cors:
    allowed-origins:
      - "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  config:
      location: java/itu/blg411/kanver:application-test.yaml